import esbuild from "esbuild";
import fs from "fs";
import path from "path";
import process from "process";
import builtins from "builtin-modules";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

function loadEnvFile() {
  const envPath = path.join(process.cwd(), ".env");
  if (!fs.existsSync(envPath)) return;
  for (const line of fs.readFileSync(envPath, "utf8").split(/\r?\n/)) {
    const m = line.match(/^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)\s*$/);
    if (!m) continue;
    let val = m[2];
    if (
      (val.startsWith('"') && val.endsWith('"')) ||
      (val.startsWith("'") && val.endsWith("'"))
    ) {
      val = val.slice(1, -1);
    }
    if (!process.env[m[1]]) process.env[m[1]] = val;
  }
}

loadEnvFile();

const prod = process.argv[2] === "production";

const clientId = process.env.GOOGLE_OAUTH_CLIENT_ID || process.env.OBSIDIAN_GDRIVE_CLIENT_ID || "";
const clientSecret =
  process.env.GOOGLE_OAUTH_CLIENT_SECRET || process.env.OBSIDIAN_GDRIVE_CLIENT_SECRET || "";
const redirectUri =
  process.env.GOOGLE_OAUTH_REDIRECT_URI ||
  process.env.OBSIDIAN_GDRIVE_REDIRECT_URI ||
  "http://127.0.0.1:42813/";

if (prod && clientId) {
  console.log(`[esbuild] Bundling OAuth Client ID into main.js (${clientId.slice(0, 12)}…)`);
} else if (prod) {
  console.warn(
    "[esbuild] No GOOGLE_OAUTH_CLIENT_ID in env/.env — Connect Google will require pasting Client ID."
  );
}

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2020",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  define: {
    __GDRIVE_CLIENT_ID__: JSON.stringify(clientId),
    __GDRIVE_CLIENT_SECRET__: JSON.stringify(clientSecret),
    __GDRIVE_REDIRECT_URI__: JSON.stringify(redirectUri),
  },
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
