/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  DESKTOP_REDIRECT_URI: () => DESKTOP_REDIRECT_URI,
  default: () => GDriveSyncPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_IGNORE = [
  ".obsidian/workspace",
  ".obsidian/workspace.json",
  ".obsidian/workspace-mobile.json",
  ".obsidian/workspaces.json",
  ".obsidian/cache",
  ".obsidian/plugins/obsidian-gdrive-sync/data.json",
  ".trash",
  ".git",
  ".DS_Store",
  "desktop.ini",
  "Thumbs.db"
].join("\n");
var DEFAULT_SETTINGS = {
  clientId: "",
  clientSecret: "",
  redirectUri: "http://127.0.0.1:42813/",
  tokens: null,
  remoteFolderName: "",
  remoteFolderId: "",
  syncIntervalSeconds: 30,
  autoSync: true,
  ignorePatterns: DEFAULT_IGNORE,
  syncIndex: { version: 1, files: {} },
  lastSyncAt: null,
  lastError: null
};
var GDriveSyncSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.pendingAuthCode = "";
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.addClass("gdrive-sync-settings");
    containerEl.createEl("h2", { text: "Google Drive Sync" });
    containerEl.createEl("p", {
      text: "Sync this vault across Android, Windows, macOS, and Linux with the same Google account and remote folder name."
    });
    new import_obsidian.Setting(containerEl).setName("Google OAuth Client ID").setDesc("From Google Cloud Console \u2192 APIs & Services \u2192 Credentials (Desktop or Web client).").addText(
      (text) => text.setPlaceholder("xxxxx.apps.googleusercontent.com").setValue(this.plugin.settings.clientId).onChange(async (value) => {
        this.plugin.settings.clientId = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Google OAuth Client Secret").setDesc("Required for Web clients. Desktop clients often leave this empty.").addText(
      (text) => text.setPlaceholder("GOCSPX-...").setValue(this.plugin.settings.clientSecret).onChange(async (value) => {
        this.plugin.settings.clientSecret = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("OAuth redirect URI").setDesc(
      "Must exactly match a redirect URI on your Google OAuth client (Web clients usually use an https URL)."
    ).addText(
      (text) => text.setPlaceholder("https://your-app.vercel.app/").setValue(this.plugin.settings.redirectUri).onChange(async (value) => {
        this.plugin.settings.redirectUri = value.trim();
        await this.plugin.saveSettings();
      })
    );
    const connected = !!this.plugin.settings.tokens?.refreshToken;
    new import_obsidian.Setting(containerEl).setName("Google account").setDesc(
      connected ? "Connected. Use the same account on every device." : import_obsidian.Platform.isMobile ? "On mobile: Connect opens the browser. Paste the redirect URL or code below." : "Connect opens your browser and finishes automatically on desktop."
    ).addButton(
      (btn) => btn.setButtonText(connected ? "Reconnect" : "Connect Google").setCta().onClick(async () => {
        try {
          await this.plugin.connectGoogle();
          this.display();
        } catch (e) {
          new import_obsidian.Notice(`Connect failed: ${String(e)}`);
        }
      })
    ).addButton(
      (btn) => btn.setButtonText("Disconnect").setDisabled(!connected).onClick(async () => {
        await this.plugin.disconnectGoogle();
        new import_obsidian.Notice("Disconnected from Google");
        this.display();
      })
    );
    if (!connected || import_obsidian.Platform.isMobile) {
      const authBox = containerEl.createDiv({ cls: "gdrive-sync-auth-box" });
      authBox.createEl("div", {
        text: "Mobile / manual auth: after signing in, copy the full redirect URL (or just the code) and paste it here."
      });
      const area = authBox.createEl("textarea");
      area.placeholder = "http://127.0.0.1:42813/?code=...   or   4/0Afc...";
      area.value = this.pendingAuthCode;
      area.addEventListener("input", () => {
        this.pendingAuthCode = area.value;
      });
      new import_obsidian.Setting(authBox).addButton(
        (btn) => btn.setButtonText("Submit auth code").setCta().onClick(async () => {
          try {
            await this.plugin.completeManualAuth(this.pendingAuthCode);
            this.pendingAuthCode = "";
            new import_obsidian.Notice("Google account connected");
            this.display();
          } catch (e) {
            new import_obsidian.Notice(`Auth failed: ${String(e)}`);
          }
        })
      );
    }
    new import_obsidian.Setting(containerEl).setName("Remote folder name").setDesc(
      "Folder under Drive \u2192 ObsidianVaults/. Use the exact same name on every device for this vault."
    ).addText(
      (text) => text.setPlaceholder(this.app.vault.getName()).setValue(this.plugin.settings.remoteFolderName).onChange(async (value) => {
        this.plugin.settings.remoteFolderName = value.trim();
        this.plugin.settings.remoteFolderId = "";
        this.plugin.settings.syncIndex.remoteFolderId = void 0;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Auto sync").setDesc("Watch local changes and poll Google Drive on an interval.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.autoSync).onChange(async (value) => {
        this.plugin.settings.autoSync = value;
        await this.plugin.saveSettings();
        this.plugin.restartAutoSync();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Sync interval (seconds)").setDesc("How often to pull remote changes. Minimum 15.").addText(
      (text) => text.setPlaceholder("30").setValue(String(this.plugin.settings.syncIntervalSeconds)).onChange(async (value) => {
        const n = Number(value);
        if (!Number.isFinite(n) || n < 15)
          return;
        this.plugin.settings.syncIntervalSeconds = Math.floor(n);
        await this.plugin.saveSettings();
        this.plugin.restartAutoSync();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Ignore patterns").setDesc("One path prefix or exact relative path per line. Matched files are never synced.").addTextArea((area) => {
      area.setValue(this.plugin.settings.ignorePatterns).onChange(async (value) => {
        this.plugin.settings.ignorePatterns = value;
        await this.plugin.saveSettings();
      });
      area.inputEl.rows = 8;
      area.inputEl.cols = 40;
    });
    new import_obsidian.Setting(containerEl).setName("Actions").addButton(
      (btn) => btn.setButtonText("Sync now").setCta().onClick(async () => {
        await this.plugin.syncNow();
      })
    ).addButton(
      (btn) => btn.setButtonText("Reset sync index").onClick(async () => {
        this.plugin.settings.syncIndex = { version: 1, files: {} };
        this.plugin.settings.remoteFolderId = "";
        await this.plugin.saveSettings();
        new import_obsidian.Notice("Sync index reset. Next sync will rebuild mapping.");
      })
    );
    if (this.plugin.settings.lastSyncAt) {
      containerEl.createEl("p", {
        text: `Last sync: ${new Date(this.plugin.settings.lastSyncAt).toLocaleString()}`
      });
    }
    if (this.plugin.settings.lastError) {
      containerEl.createEl("p", {
        cls: "mod-warning",
        text: `Last error: ${this.plugin.settings.lastError}`
      });
    }
  }
};

// src/auth/google-oauth.ts
var import_obsidian2 = require("obsidian");
var AUTH_ENDPOINT = "https://accounts.google.com/o/oauth2/v2/auth";
var TOKEN_ENDPOINT = "https://oauth2.googleapis.com/token";
var REVOKE_ENDPOINT = "https://oauth2.googleapis.com/revoke";
var DRIVE_SCOPES = [
  "https://www.googleapis.com/auth/drive.file",
  "openid",
  "email"
].join(" ");
var DESKTOP_REDIRECT_PORT = 42813;
var DESKTOP_REDIRECT_URI = `http://127.0.0.1:${DESKTOP_REDIRECT_PORT}/`;
function randomState() {
  const arr = new Uint8Array(16);
  crypto.getRandomValues(arr);
  return Array.from(arr, (b) => b.toString(16).padStart(2, "0")).join("");
}
function buildAuthUrl(config, redirectUri, state) {
  const params = new URLSearchParams({
    client_id: config.clientId,
    redirect_uri: redirectUri,
    response_type: "code",
    scope: DRIVE_SCOPES,
    access_type: "offline",
    prompt: "consent",
    state
  });
  return `${AUTH_ENDPOINT}?${params.toString()}`;
}
function extractCodeFromInput(input) {
  const trimmed = input.trim();
  if (!trimmed)
    throw new Error("Empty authorization input");
  if (trimmed.startsWith("http://") || trimmed.startsWith("https://") || trimmed.startsWith("obsidian://")) {
    try {
      const url = new URL(trimmed);
      const code = url.searchParams.get("code");
      if (code)
        return code;
      const err = url.searchParams.get("error");
      if (err)
        throw new Error(`OAuth error: ${err}`);
    } catch (e) {
      if (e instanceof Error && e.message.startsWith("OAuth error"))
        throw e;
    }
  }
  if (/^[\w./\-]+$/.test(trimmed) && trimmed.length > 20) {
    return trimmed;
  }
  const match = trimmed.match(/[?&#]code=([^&\s]+)/);
  if (match?.[1])
    return decodeURIComponent(match[1]);
  throw new Error("Could not find authorization code in the pasted text");
}
async function exchangeCode(config, code, redirectUri) {
  const body = new URLSearchParams({
    code,
    client_id: config.clientId,
    redirect_uri: redirectUri,
    grant_type: "authorization_code"
  });
  if (config.clientSecret) {
    body.set("client_secret", config.clientSecret);
  }
  const res = await (0, import_obsidian2.requestUrl)({
    url: TOKEN_ENDPOINT,
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    body: body.toString(),
    throw: false
  });
  if (res.status >= 400) {
    throw new Error(`Token exchange failed (${res.status}): ${res.text}`);
  }
  const data = res.json;
  if (!data.access_token) {
    throw new Error("Token exchange returned no access_token");
  }
  return {
    accessToken: data.access_token,
    refreshToken: data.refresh_token ?? "",
    expiresAt: Date.now() + (data.expires_in ?? 3600) * 1e3 - 6e4,
    tokenType: data.token_type ?? "Bearer",
    scope: data.scope
  };
}
async function refreshAccessToken(config, refreshToken) {
  const body = new URLSearchParams({
    refresh_token: refreshToken,
    client_id: config.clientId,
    grant_type: "refresh_token"
  });
  if (config.clientSecret) {
    body.set("client_secret", config.clientSecret);
  }
  const res = await (0, import_obsidian2.requestUrl)({
    url: TOKEN_ENDPOINT,
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    body: body.toString(),
    throw: false
  });
  if (res.status >= 400) {
    throw new Error(`Token refresh failed (${res.status}): ${res.text}`);
  }
  const data = res.json;
  return {
    accessToken: data.access_token,
    refreshToken: data.refresh_token ?? refreshToken,
    expiresAt: Date.now() + (data.expires_in ?? 3600) * 1e3 - 6e4,
    tokenType: data.token_type ?? "Bearer",
    scope: data.scope
  };
}
async function revokeToken(token) {
  try {
    await (0, import_obsidian2.requestUrl)({
      url: `${REVOKE_ENDPOINT}?token=${encodeURIComponent(token)}`,
      method: "POST",
      throw: false
    });
  } catch {
  }
}
var GoogleOAuth = class {
  constructor() {
    this.pendingState = null;
    this.pendingRedirectUri = DESKTOP_REDIRECT_URI;
    this.serverCloser = null;
  }
  getRedirectUri() {
    return this.pendingRedirectUri;
  }
  getPendingState() {
    return this.pendingState;
  }
  beginAuth(config) {
    this.cancelPending();
    this.pendingState = randomState();
    this.pendingRedirectUri = (config.redirectUri || DESKTOP_REDIRECT_URI).trim() || DESKTOP_REDIRECT_URI;
    const authUrl = buildAuthUrl(config, this.pendingRedirectUri, this.pendingState);
    return { authUrl, redirectUri: this.pendingRedirectUri, state: this.pendingState };
  }
  usesLoopback(redirectUri) {
    return redirectUri.startsWith("http://127.0.0.1:") || redirectUri.startsWith("http://localhost:");
  }
  async connectDesktop(config) {
    if (!import_obsidian2.Platform.isDesktopApp) {
      throw new Error("Loopback OAuth is only available on desktop");
    }
    const { authUrl, redirectUri, state } = this.beginAuth(config);
    if (!this.usesLoopback(redirectUri)) {
      window.open(authUrl);
      throw new Error(
        "Browser opened for Google sign-in. When redirected back to your site, Obsidian should open automatically \u2014 or paste the URL/code in settings."
      );
    }
    const code = await new Promise((resolve, reject) => {
      const http = require("http");
      const server = http.createServer((req, res) => {
        try {
          const url = new URL(req.url ?? "/", `http://127.0.0.1:${DESKTOP_REDIRECT_PORT}`);
          const err = url.searchParams.get("error");
          const codeParam = url.searchParams.get("code");
          const st = url.searchParams.get("state");
          res.writeHead(200, { "Content-Type": "text/html; charset=utf-8" });
          if (err) {
            res.end(`<h1>Auth failed</h1><p>${err}</p><p>You can close this window.</p>`);
            cleanup();
            reject(new Error(`OAuth error: ${err}`));
            return;
          }
          if (!codeParam) {
            res.end("<h1>Missing code</h1>");
            return;
          }
          if (st !== state) {
            res.end("<h1>Invalid state</h1>");
            cleanup();
            reject(new Error("OAuth state mismatch"));
            return;
          }
          res.end(
            "<h1>Connected</h1><p>Google Drive Sync is authorized. Return to Obsidian.</p>"
          );
          cleanup();
          resolve(codeParam);
        } catch (e) {
          cleanup();
          reject(e);
        }
      });
      const cleanup = () => {
        try {
          server.close();
        } catch {
        }
        this.serverCloser = null;
      };
      this.serverCloser = cleanup;
      server.listen(DESKTOP_REDIRECT_PORT, "127.0.0.1", () => {
        window.open(authUrl);
      });
      server.on("error", (e) => {
        cleanup();
        reject(e);
      });
      setTimeout(() => {
        cleanup();
        reject(new Error("OAuth timed out \u2014 try again or paste the auth code manually"));
      }, 5 * 60 * 1e3);
    });
    const tokens = await exchangeCode(config, code, redirectUri);
    if (!tokens.refreshToken) {
      throw new Error(
        "No refresh token received. Remove the app from https://myaccount.google.com/permissions and connect again."
      );
    }
    this.pendingState = null;
    return tokens;
  }
  /** Open browser for mobile / manual flow. */
  openBrowserAuth(config) {
    const { authUrl, redirectUri } = this.beginAuth(config);
    window.open(authUrl);
    return { redirectUri };
  }
  async completeWithCode(config, rawInput) {
    const code = extractCodeFromInput(rawInput);
    const redirectUri = this.pendingRedirectUri || DESKTOP_REDIRECT_URI;
    const tokens = await exchangeCode(config, code, redirectUri);
    if (!tokens.refreshToken) {
      throw new Error(
        "No refresh token received. Revoke prior access at Google Account permissions and retry with prompt=consent."
      );
    }
    this.pendingState = null;
    return tokens;
  }
  cancelPending() {
    if (this.serverCloser) {
      this.serverCloser();
      this.serverCloser = null;
    }
  }
};

// src/drive/drive-client.ts
var import_obsidian3 = require("obsidian");
var DRIVE_API = "https://www.googleapis.com/drive/v3";
var UPLOAD_API = "https://www.googleapis.com/upload/drive/v3";
var FOLDER_MIME = "application/vnd.google-apps.folder";
var ROOT_FOLDER_NAME = "ObsidianVaults";
var DriveClient = class {
  constructor(config, tokens, onTokensUpdated) {
    this.config = config;
    this.tokens = tokens;
    this.onTokensUpdated = onTokensUpdated;
  }
  updateTokens(tokens) {
    this.tokens = tokens;
  }
  async accessToken() {
    if (Date.now() >= this.tokens.expiresAt - 5e3) {
      const refreshed = await refreshAccessToken(this.config, this.tokens.refreshToken);
      this.tokens = refreshed;
      await this.onTokensUpdated(refreshed);
    }
    return this.tokens.accessToken;
  }
  async api(path, options = {}) {
    return this.requestWithRetry(path, options, 0);
  }
  async requestWithRetry(path, options, attempt) {
    const token = await this.accessToken();
    let url = options.rawUrl ?? `${DRIVE_API}${path}`;
    if (options.query) {
      const qs = new URLSearchParams(options.query);
      url += (url.includes("?") ? "&" : "?") + qs.toString();
    }
    const res = await (0, import_obsidian3.requestUrl)({
      url,
      method: options.method ?? "GET",
      headers: {
        Authorization: `Bearer ${token}`,
        ...options.headers ?? {}
      },
      body: options.body,
      throw: false
    });
    if (res.status === 401 && attempt < 1) {
      const refreshed = await refreshAccessToken(this.config, this.tokens.refreshToken);
      this.tokens = refreshed;
      await this.onTokensUpdated(refreshed);
      return this.requestWithRetry(path, options, attempt + 1);
    }
    if ((res.status === 403 || res.status === 429) && attempt < 5) {
      const delay = Math.min(3e4, 500 * Math.pow(2, attempt));
      await sleep(delay);
      return this.requestWithRetry(path, options, attempt + 1);
    }
    if (res.status >= 400) {
      throw new Error(`Drive API ${res.status}: ${res.text}`);
    }
    if (res.status === 204 || !res.text) {
      return void 0;
    }
    try {
      return res.json;
    } catch {
      return void 0;
    }
  }
  async ensureVaultFolder(vaultFolderName) {
    const rootId = await this.findOrCreateFolder(ROOT_FOLDER_NAME, "root");
    const folderId = await this.findOrCreateFolder(vaultFolderName, rootId);
    return { rootId, folderId };
  }
  async findOrCreateFolder(name, parentId) {
    const existing = await this.findChild(name, parentId, FOLDER_MIME);
    if (existing)
      return existing.id;
    const created = await this.api("/files", {
      method: "POST",
      query: { fields: "id,name,mimeType" },
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        name,
        mimeType: FOLDER_MIME,
        parents: [parentId]
      })
    });
    return created.id;
  }
  async findChild(name, parentId, mimeType) {
    const escaped = name.replace(/\\/g, "\\\\").replace(/'/g, "\\'");
    let q = `name='${escaped}' and '${parentId}' in parents and trashed=false`;
    if (mimeType)
      q += ` and mimeType='${mimeType}'`;
    const result = await this.api("/files", {
      query: {
        q,
        fields: "files(id,name,mimeType,modifiedTime,size,md5Checksum,appProperties)",
        pageSize: "10",
        spaces: "drive"
      }
    });
    return result.files?.[0] ?? null;
  }
  async listFolderRecursive(folderId) {
    const out = /* @__PURE__ */ new Map();
    await this.walk(folderId, "", out);
    return out;
  }
  async walk(folderId, prefix, out) {
    let pageToken;
    do {
      const query = {
        q: `'${folderId}' in parents and trashed=false`,
        fields: "nextPageToken,files(id,name,mimeType,modifiedTime,size,md5Checksum,appProperties,parents)",
        pageSize: "1000",
        spaces: "drive"
      };
      if (pageToken)
        query.pageToken = pageToken;
      const page = await this.api("/files", {
        query
      });
      for (const file of page.files ?? []) {
        const path = prefix ? `${prefix}/${file.name}` : file.name;
        if (file.mimeType === FOLDER_MIME) {
          await this.walk(file.id, path, out);
        } else {
          out.set(path, file);
        }
      }
      pageToken = page.nextPageToken;
    } while (pageToken);
  }
  /** Ensure nested folders exist for a vault-relative file path; return parent folder id. */
  async ensureParentPath(rootFolderId, relativeFilePath) {
    const parts = relativeFilePath.replace(/\\/g, "/").split("/");
    parts.pop();
    let parent = rootFolderId;
    for (const part of parts) {
      if (!part)
        continue;
      parent = await this.findOrCreateFolder(part, parent);
    }
    return parent;
  }
  async uploadNew(parentId, name, content, mimeType, appProperties) {
    const metadata = {
      name,
      parents: [parentId],
      appProperties
    };
    if (content.byteLength < 5 * 1024 * 1024) {
      return this.multipartUpload("POST", `${UPLOAD_API}/files?uploadType=multipart&fields=id,name,mimeType,modifiedTime,size,md5Checksum,appProperties`, metadata, content, mimeType);
    }
    return this.resumableUpload("POST", parentId, name, content, mimeType, appProperties);
  }
  async updateFile(fileId, content, mimeType, appProperties) {
    if (appProperties) {
      await this.api(`/files/${fileId}`, {
        method: "PATCH",
        query: { fields: "id" },
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ appProperties })
      });
    }
    if (content.byteLength < 5 * 1024 * 1024) {
      return this.multipartUpload(
        "PATCH",
        `${UPLOAD_API}/files/${fileId}?uploadType=multipart&fields=id,name,mimeType,modifiedTime,size,md5Checksum,appProperties`,
        {},
        content,
        mimeType
      );
    }
    const token = await this.accessToken();
    const start = await (0, import_obsidian3.requestUrl)({
      url: `${UPLOAD_API}/files/${fileId}?uploadType=resumable&fields=id,name,mimeType,modifiedTime,size,md5Checksum,appProperties`,
      method: "PATCH",
      headers: {
        Authorization: `Bearer ${token}`,
        "Content-Type": "application/json; charset=UTF-8",
        "X-Upload-Content-Type": mimeType,
        "X-Upload-Content-Length": String(content.byteLength)
      },
      body: JSON.stringify({}),
      throw: false
    });
    if (start.status >= 400) {
      throw new Error(`Resumable start failed: ${start.status} ${start.text}`);
    }
    const sessionUrl = start.headers["location"] || start.headers["Location"];
    if (!sessionUrl)
      throw new Error("No resumable session URL");
    const put = await (0, import_obsidian3.requestUrl)({
      url: sessionUrl,
      method: "PUT",
      headers: {
        "Content-Type": mimeType,
        "Content-Length": String(content.byteLength)
      },
      body: content,
      throw: false
    });
    if (put.status >= 400) {
      throw new Error(`Resumable upload failed: ${put.status} ${put.text}`);
    }
    return put.json;
  }
  async multipartUpload(method, url, metadata, content, mimeType) {
    const boundary = "obsidian_gdrive_sync_" + Date.now();
    const metaPart = `--${boundary}\r
Content-Type: application/json; charset=UTF-8\r
\r
${JSON.stringify(metadata)}\r
`;
    const fileHeader = `--${boundary}\r
Content-Type: ${mimeType}\r
\r
`;
    const end = `\r
--${boundary}--`;
    const metaBytes = new TextEncoder().encode(metaPart + fileHeader);
    const endBytes = new TextEncoder().encode(end);
    const body = new Uint8Array(metaBytes.length + content.byteLength + endBytes.length);
    body.set(metaBytes, 0);
    body.set(new Uint8Array(content), metaBytes.length);
    body.set(endBytes, metaBytes.length + content.byteLength);
    const bodyBuffer = body.buffer.slice(body.byteOffset, body.byteOffset + body.byteLength);
    const token = await this.accessToken();
    const res = await (0, import_obsidian3.requestUrl)({
      url,
      method,
      headers: {
        Authorization: `Bearer ${token}`,
        "Content-Type": `multipart/related; boundary=${boundary}`
      },
      body: bodyBuffer,
      throw: false
    });
    if (res.status === 403 || res.status === 429) {
      await sleep(1e3);
      return this.multipartUpload(method, url, metadata, content, mimeType);
    }
    if (res.status >= 400) {
      throw new Error(`Upload failed ${res.status}: ${res.text}`);
    }
    return res.json;
  }
  async resumableUpload(_method, parentId, name, content, mimeType, appProperties) {
    const token = await this.accessToken();
    const start = await (0, import_obsidian3.requestUrl)({
      url: `${UPLOAD_API}/files?uploadType=resumable&fields=id,name,mimeType,modifiedTime,size,md5Checksum,appProperties`,
      method: "POST",
      headers: {
        Authorization: `Bearer ${token}`,
        "Content-Type": "application/json; charset=UTF-8",
        "X-Upload-Content-Type": mimeType,
        "X-Upload-Content-Length": String(content.byteLength)
      },
      body: JSON.stringify({
        name,
        parents: [parentId],
        appProperties
      }),
      throw: false
    });
    if (start.status >= 400) {
      throw new Error(`Resumable start failed: ${start.status} ${start.text}`);
    }
    const sessionUrl = start.headers["location"] || start.headers["Location"];
    if (!sessionUrl)
      throw new Error("No resumable session URL");
    const put = await (0, import_obsidian3.requestUrl)({
      url: sessionUrl,
      method: "PUT",
      headers: {
        "Content-Type": mimeType,
        "Content-Length": String(content.byteLength)
      },
      body: content,
      throw: false
    });
    if (put.status >= 400) {
      throw new Error(`Resumable upload failed: ${put.status} ${put.text}`);
    }
    return put.json;
  }
  async download(fileId) {
    const token = await this.accessToken();
    const res = await (0, import_obsidian3.requestUrl)({
      url: `${DRIVE_API}/files/${fileId}?alt=media`,
      method: "GET",
      headers: { Authorization: `Bearer ${token}` },
      throw: false
    });
    if (res.status >= 400) {
      throw new Error(`Download failed ${res.status}: ${res.text}`);
    }
    return res.arrayBuffer;
  }
  async trash(fileId) {
    await this.api(`/files/${fileId}`, {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ trashed: true }),
      query: { fields: "id" }
    });
  }
  async rename(fileId, newName) {
    await this.api(`/files/${fileId}`, {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ name: newName }),
      query: { fields: "id,name" }
    });
  }
  async getStartPageToken() {
    const res = await this.api("/changes/startPageToken", {
      query: { supportsAllDrives: "false" }
    });
    return res.startPageToken;
  }
  guessMime(path) {
    const lower = path.toLowerCase();
    if (lower.endsWith(".md"))
      return "text/markdown";
    if (lower.endsWith(".json"))
      return "application/json";
    if (lower.endsWith(".png"))
      return "image/png";
    if (lower.endsWith(".jpg") || lower.endsWith(".jpeg"))
      return "image/jpeg";
    if (lower.endsWith(".gif"))
      return "image/gif";
    if (lower.endsWith(".webp"))
      return "image/webp";
    if (lower.endsWith(".pdf"))
      return "application/pdf";
    if (lower.endsWith(".svg"))
      return "image/svg+xml";
    if (lower.endsWith(".css"))
      return "text/css";
    if (lower.endsWith(".js"))
      return "application/javascript";
    if (lower.endsWith(".html"))
      return "text/html";
    if (lower.endsWith(".txt"))
      return "text/plain";
    return "application/octet-stream";
  }
};
function sleep(ms) {
  return new Promise((r) => setTimeout(r, ms));
}

// src/sync/sync-engine.ts
var import_obsidian4 = require("obsidian");

// src/util/paths.ts
function normalizeVaultPath(path) {
  return path.replace(/\\/g, "/").replace(/^\/+/, "").replace(/\/+$/, "");
}
function dirname(path) {
  const n = normalizeVaultPath(path);
  const i = n.lastIndexOf("/");
  return i === -1 ? "" : n.slice(0, i);
}
function basename(path) {
  const n = normalizeVaultPath(path);
  const i = n.lastIndexOf("/");
  return i === -1 ? n : n.slice(i + 1);
}
function joinPath(...parts) {
  return parts.map((p) => normalizeVaultPath(p)).filter(Boolean).join("/");
}

// src/sync/ignore.ts
function parseIgnorePatterns(raw) {
  return raw.split(/\r?\n/).map((l) => normalizeVaultPath(l.trim())).filter((l) => l.length > 0 && !l.startsWith("#"));
}
function isIgnored(path, patterns) {
  const p = normalizeVaultPath(path);
  if (p.endsWith("(conflict") || / \(conflict \d{4}-\d{2}-\d{2}[^)]*\)/.test(p)) {
  }
  for (const pattern of patterns) {
    if (p === pattern)
      return true;
    if (p.startsWith(pattern.endsWith("/") ? pattern : pattern + "/"))
      return true;
    if (pattern.startsWith("*.") && p.toLowerCase().endsWith(pattern.slice(1).toLowerCase())) {
      return true;
    }
  }
  return false;
}

// src/sync/index-store.ts
function getEntry(index, path) {
  return index.files[path];
}
function setEntry(index, path, entry) {
  index.files[path] = entry;
}
function removeEntry(index, path) {
  delete index.files[path];
}
function renameEntry(index, oldPath, newPath) {
  const entry = index.files[oldPath];
  if (!entry)
    return;
  delete index.files[oldPath];
  index.files[newPath] = entry;
}

// src/sync/conflict.ts
function conflictPath(originalPath, when = /* @__PURE__ */ new Date()) {
  const path = normalizeVaultPath(originalPath);
  const dir = dirname(path);
  const name = basename(path);
  const dot = name.lastIndexOf(".");
  const date = when.toISOString().slice(0, 10);
  let conflictName;
  if (dot > 0) {
    conflictName = `${name.slice(0, dot)} (conflict ${date})${name.slice(dot)}`;
  } else {
    conflictName = `${name} (conflict ${date})`;
  }
  return dir ? joinPath(dir, conflictName) : conflictName;
}
function uniqueConflictPath(originalPath, exists) {
  let candidate = conflictPath(originalPath);
  if (!exists(candidate))
    return candidate;
  const stamp = (/* @__PURE__ */ new Date()).toISOString().replace(/[:.]/g, "-");
  const path = normalizeVaultPath(originalPath);
  const dir = dirname(path);
  const name = basename(path);
  const dot = name.lastIndexOf(".");
  const conflictName = dot > 0 ? `${name.slice(0, dot)} (conflict ${stamp})${name.slice(dot)}` : `${name} (conflict ${stamp})`;
  candidate = dir ? joinPath(dir, conflictName) : conflictName;
  return candidate;
}

// src/util/hash.ts
async function sha256Hex(data) {
  let bytes;
  if (typeof data === "string") {
    bytes = new TextEncoder().encode(data);
  } else if (data instanceof Uint8Array) {
    bytes = data;
  } else {
    bytes = new Uint8Array(data);
  }
  const copy = new Uint8Array(bytes.byteLength);
  copy.set(bytes);
  const digest = await crypto.subtle.digest("SHA-256", copy.buffer);
  return Array.from(new Uint8Array(digest)).map((b) => b.toString(16).padStart(2, "0")).join("");
}

// src/sync/sync-engine.ts
var SyncEngine = class {
  constructor(app, settings, callbacks) {
    this.drive = null;
    this.running = false;
    this.queued = false;
    this.debounceTimer = null;
    this.suppressWatch = false;
    this.pendingLocal = /* @__PURE__ */ new Set();
    this.pendingDeletes = /* @__PURE__ */ new Set();
    this.pendingRenames = [];
    this.app = app;
    this.settings = settings;
    this.callbacks = callbacks;
  }
  setDrive(drive) {
    this.drive = drive;
  }
  updateSettings(settings) {
    this.settings = settings;
  }
  scheduleSync(delayMs = 1500) {
    if (!this.settings.autoSync)
      return;
    if (this.debounceTimer)
      clearTimeout(this.debounceTimer);
    this.debounceTimer = setTimeout(() => {
      void this.sync();
    }, delayMs);
  }
  onLocalCreateOrModify(file) {
    if (this.suppressWatch)
      return;
    if (!(file instanceof import_obsidian4.TFile))
      return;
    const path = normalizeVaultPath(file.path);
    if (this.shouldIgnore(path))
      return;
    this.pendingLocal.add(path);
    this.scheduleSync();
  }
  onLocalDelete(file) {
    if (this.suppressWatch)
      return;
    const path = normalizeVaultPath(file.path);
    if (this.shouldIgnore(path))
      return;
    this.pendingLocal.delete(path);
    this.pendingDeletes.add(path);
    this.scheduleSync();
  }
  onLocalRename(file, oldPath) {
    if (this.suppressWatch)
      return;
    const from = normalizeVaultPath(oldPath);
    const to = normalizeVaultPath(file.path);
    if (this.shouldIgnore(from) && this.shouldIgnore(to))
      return;
    this.pendingRenames.push({ oldPath: from, newPath: to });
    this.pendingLocal.add(to);
    this.pendingDeletes.delete(to);
    this.scheduleSync();
  }
  async sync() {
    if (this.running) {
      this.queued = true;
      return;
    }
    if (!this.drive) {
      this.callbacks.onStatus("error", "Not connected to Google");
      return;
    }
    if (!this.settings.clientId) {
      this.callbacks.onStatus("error", "Missing Client ID");
      return;
    }
    this.running = true;
    this.callbacks.onStatus("syncing", "Syncing\u2026");
    try {
      const folderName = this.settings.remoteFolderName.trim() || this.app.vault.getName() || "Vault";
      let folderId = this.settings.remoteFolderId || this.settings.syncIndex.remoteFolderId;
      if (!folderId) {
        const { rootId, folderId: id } = await this.drive.ensureVaultFolder(folderName);
        folderId = id;
        this.settings.remoteFolderId = id;
        this.settings.remoteFolderName = folderName;
        this.settings.syncIndex.remoteFolderId = id;
        this.settings.syncIndex.remoteRootId = rootId;
        if (!this.settings.syncIndex.changeToken) {
          this.settings.syncIndex.changeToken = await this.drive.getStartPageToken();
        }
        await this.callbacks.saveSettings();
      }
      const renames = this.pendingRenames.splice(0);
      for (const { oldPath, newPath } of renames) {
        await this.handleRename(folderId, oldPath, newPath);
      }
      const deletes = [...this.pendingDeletes];
      this.pendingDeletes.clear();
      for (const path of deletes) {
        await this.pushDelete(path);
      }
      await this.reconcile(folderId);
      this.settings.lastSyncAt = Date.now();
      this.settings.lastError = null;
      await this.callbacks.saveSettings();
      this.callbacks.onStatus("idle", "Synced");
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      this.settings.lastError = msg;
      await this.callbacks.saveSettings();
      this.callbacks.onStatus("error", msg);
    } finally {
      this.running = false;
      if (this.queued) {
        this.queued = false;
        this.scheduleSync(500);
      }
    }
  }
  shouldIgnore(path) {
    return isIgnored(path, parseIgnorePatterns(this.settings.ignorePatterns));
  }
  async handleRename(folderId, oldPath, newPath) {
    if (!this.drive)
      return;
    const index = this.settings.syncIndex;
    const entry = getEntry(index, oldPath);
    if (entry?.driveFileId) {
      try {
        if (dirname(oldPath) === dirname(newPath)) {
          await this.drive.rename(entry.driveFileId, newPath.split("/").pop());
          renameEntry(index, oldPath, newPath);
        } else {
          await this.drive.trash(entry.driveFileId);
          removeEntry(index, oldPath);
          this.pendingLocal.add(newPath);
        }
      } catch {
        removeEntry(index, oldPath);
        this.pendingLocal.add(newPath);
      }
    } else {
      this.pendingLocal.add(newPath);
    }
  }
  async pushDelete(path) {
    if (!this.drive)
      return;
    const entry = getEntry(this.settings.syncIndex, path);
    if (entry?.driveFileId) {
      try {
        await this.drive.trash(entry.driveFileId);
      } catch {
      }
    }
    removeEntry(this.settings.syncIndex, path);
  }
  async reconcile(folderId) {
    if (!this.drive)
      return;
    const index = this.settings.syncIndex;
    const remoteMap = await this.drive.listFolderRecursive(folderId);
    const localFiles = this.app.vault.getFiles();
    const localMap = /* @__PURE__ */ new Map();
    for (const f of localFiles) {
      const p = normalizeVaultPath(f.path);
      if (!this.shouldIgnore(p))
        localMap.set(p, f);
    }
    const pending = [...this.pendingLocal];
    this.pendingLocal.clear();
    for (const path of pending) {
      const file = localMap.get(path);
      if (file)
        await this.pushFile(folderId, file, index, remoteMap);
    }
    const allPaths = /* @__PURE__ */ new Set([
      ...localMap.keys(),
      ...remoteMap.keys(),
      ...Object.keys(index.files)
    ]);
    for (const path of allPaths) {
      if (this.shouldIgnore(path))
        continue;
      if (path === ".gdrive-sync-meta.json")
        continue;
      const local = localMap.get(path);
      const remote = remoteMap.get(path);
      const entry = getEntry(index, path);
      if (local && !remote) {
        await this.pushFile(folderId, local, index, remoteMap);
        continue;
      }
      if (!local && remote) {
        if (entry && entry.driveFileId === remote.id) {
          await this.drive.trash(remote.id);
          removeEntry(index, path);
        } else {
          await this.pullFile(path, remote, index);
        }
        continue;
      }
      if (!local && !remote) {
        if (entry)
          removeEntry(index, path);
        continue;
      }
      if (local && remote) {
        await this.mergeFile(folderId, local, remote, index);
      }
    }
  }
  async readLocal(file) {
    const data = await this.app.vault.readBinary(file);
    const hash = await sha256Hex(data);
    return {
      data,
      hash,
      mtime: file.stat.mtime,
      size: file.stat.size
    };
  }
  async pushFile(folderId, file, index, remoteMap) {
    if (!this.drive)
      return;
    const path = normalizeVaultPath(file.path);
    const { data, hash, mtime, size } = await this.readLocal(file);
    const mime = this.drive.guessMime(path);
    const props = { vaultPath: path, sha256: hash };
    const entry = getEntry(index, path);
    const remote = remoteMap.get(path);
    if (entry?.driveFileId || remote?.id) {
      const id = entry?.driveFileId || remote.id;
      if (entry?.hash === hash) {
        if (!entry.driveFileId && remote) {
          setEntry(index, path, { driveFileId: remote.id, hash, mtime, size });
        }
        return;
      }
      const meta2 = await this.drive.updateFile(id, data, mime, props);
      setEntry(index, path, {
        driveFileId: meta2.id,
        hash,
        mtime,
        size
      });
      remoteMap.set(path, meta2);
      return;
    }
    const parentId = await this.drive.ensureParentPath(folderId, path);
    const name = path.split("/").pop();
    const meta = await this.drive.uploadNew(parentId, name, data, mime, props);
    setEntry(index, path, {
      driveFileId: meta.id,
      hash,
      mtime,
      size
    });
    remoteMap.set(path, meta);
  }
  async pullFile(path, remote, index) {
    if (!this.drive)
      return;
    const data = await this.drive.download(remote.id);
    const hash = await sha256Hex(data);
    const mtime = remote.modifiedTime ? Date.parse(remote.modifiedTime) : Date.now();
    this.suppressWatch = true;
    try {
      await this.writeBinaryAtomic(path, data);
    } finally {
      this.suppressWatch = false;
    }
    setEntry(index, path, {
      driveFileId: remote.id,
      hash,
      mtime,
      size: data.byteLength
    });
  }
  async mergeFile(folderId, local, remote, index) {
    if (!this.drive)
      return;
    const path = normalizeVaultPath(local.path);
    const localInfo = await this.readLocal(local);
    const entry = getEntry(index, path);
    const remoteMtime = remote.modifiedTime ? Date.parse(remote.modifiedTime) : 0;
    const remoteHashProp = remote.appProperties?.sha256;
    if (entry && entry.hash === localInfo.hash && entry.driveFileId === remote.id) {
      if (remoteHashProp && remoteHashProp === localInfo.hash)
        return;
      if (remote.md5Checksum && entry.hash === localInfo.hash)
        return;
    }
    let remoteData = null;
    let remoteHash = remoteHashProp ?? "";
    const needRemoteBytes = !remoteHash || entry && entry.hash !== localInfo.hash && (!remoteHash || remoteHash !== entry.hash);
    if (!remoteHash || needRemoteBytes) {
      remoteData = await this.drive.download(remote.id);
      remoteHash = await sha256Hex(remoteData);
    }
    if (localInfo.hash === remoteHash) {
      setEntry(index, path, {
        driveFileId: remote.id,
        hash: localInfo.hash,
        mtime: Math.max(localInfo.mtime, remoteMtime),
        size: localInfo.size
      });
      return;
    }
    const localChanged = !entry || entry.hash !== localInfo.hash;
    const remoteChanged = !entry || entry.hash !== remoteHash;
    if (localChanged && remoteChanged) {
      if (!remoteData)
        remoteData = await this.drive.download(remote.id);
      const conflict = uniqueConflictPath(path, (p) => !!this.app.vault.getAbstractFileByPath(p));
      this.suppressWatch = true;
      try {
        await this.writeBinaryAtomic(conflict, remoteData);
      } finally {
        this.suppressWatch = false;
      }
      const meta = await this.drive.updateFile(
        remote.id,
        localInfo.data,
        this.drive.guessMime(path),
        { vaultPath: path, sha256: localInfo.hash }
      );
      setEntry(index, path, {
        driveFileId: meta.id,
        hash: localInfo.hash,
        mtime: localInfo.mtime,
        size: localInfo.size
      });
      const conflictFile = this.app.vault.getAbstractFileByPath(conflict);
      if (conflictFile instanceof import_obsidian4.TFile) {
        await this.pushFile(folderId, conflictFile, index, /* @__PURE__ */ new Map());
      }
      return;
    }
    if (remoteChanged && !localChanged) {
      if (!remoteData)
        remoteData = await this.drive.download(remote.id);
      this.suppressWatch = true;
      try {
        await this.writeBinaryAtomic(path, remoteData);
      } finally {
        this.suppressWatch = false;
      }
      setEntry(index, path, {
        driveFileId: remote.id,
        hash: remoteHash,
        mtime: remoteMtime || Date.now(),
        size: remoteData.byteLength
      });
      return;
    }
    if (localChanged && !remoteChanged) {
      const meta = await this.drive.updateFile(
        remote.id,
        localInfo.data,
        this.drive.guessMime(path),
        { vaultPath: path, sha256: localInfo.hash }
      );
      setEntry(index, path, {
        driveFileId: meta.id,
        hash: localInfo.hash,
        mtime: localInfo.mtime,
        size: localInfo.size
      });
      return;
    }
    if (localInfo.mtime >= remoteMtime) {
      const meta = await this.drive.updateFile(
        remote.id,
        localInfo.data,
        this.drive.guessMime(path),
        { vaultPath: path, sha256: localInfo.hash }
      );
      setEntry(index, path, {
        driveFileId: meta.id,
        hash: localInfo.hash,
        mtime: localInfo.mtime,
        size: localInfo.size
      });
    } else {
      if (!remoteData)
        remoteData = await this.drive.download(remote.id);
      this.suppressWatch = true;
      try {
        await this.writeBinaryAtomic(path, remoteData);
      } finally {
        this.suppressWatch = false;
      }
      setEntry(index, path, {
        driveFileId: remote.id,
        hash: remoteHash || await sha256Hex(remoteData),
        mtime: remoteMtime,
        size: remoteData.byteLength
      });
    }
  }
  async writeBinaryAtomic(path, data) {
    const normalized = (0, import_obsidian4.normalizePath)(path);
    const folder = dirname(normalized);
    if (folder) {
      await this.ensureLocalFolder(folder);
    }
    const existing = this.app.vault.getAbstractFileByPath(normalized);
    if (existing instanceof import_obsidian4.TFile) {
      await this.app.vault.modifyBinary(existing, data);
      return;
    }
    await this.app.vault.createBinary(normalized, data);
  }
  async ensureLocalFolder(folderPath) {
    const normalized = (0, import_obsidian4.normalizePath)(folderPath);
    const existing = this.app.vault.getAbstractFileByPath(normalized);
    if (existing instanceof import_obsidian4.TFolder)
      return;
    if (existing)
      return;
    const parts = normalized.split("/");
    let cur = "";
    for (const part of parts) {
      cur = cur ? `${cur}/${part}` : part;
      const abs = this.app.vault.getAbstractFileByPath(cur);
      if (!abs) {
        await this.app.vault.createFolder(cur);
      }
    }
  }
};

// src/main.ts
var RIBBON_ICON_ID = "gdrive-sync-icon";
var GDriveSyncPlugin = class extends import_obsidian5.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
    this.oauth = new GoogleOAuth();
    this.drive = null;
    this.engine = null;
    this.statusBarEl = null;
    this.pollTimer = null;
    this.status = "idle";
    this.statusDetail = "";
  }
  async onload() {
    await this.loadSettings();
    (0, import_obsidian5.addIcon)(
      RIBBON_ICON_ID,
      `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M18 10h-1.26A8 8 0 1 0 9 20h9a5 5 0 0 0 0-10z"/><path d="M12 12v5"/><path d="m9 14 3-3 3 3"/></svg>`
    );
    this.statusBarEl = this.addStatusBarItem();
    this.statusBarEl.addClass("gdrive-sync-status");
    this.statusBarEl.setText("GDrive: Idle");
    this.statusBarEl.onclick = () => void this.syncNow();
    this.addRibbonIcon(RIBBON_ICON_ID, "Google Drive Sync Now", () => {
      void this.syncNow();
    });
    this.addCommand({
      id: "gdrive-sync-now",
      name: "Sync now",
      callback: () => void this.syncNow()
    });
    this.addCommand({
      id: "gdrive-connect",
      name: "Connect Google account",
      callback: () => void this.connectGoogle()
    });
    this.addCommand({
      id: "gdrive-disconnect",
      name: "Disconnect Google account",
      callback: () => void this.disconnectGoogle()
    });
    this.addCommand({
      id: "gdrive-open-settings",
      name: "Open Google Drive Sync settings",
      callback: () => {
        this.app.setting.open();
        this.app.setting.openTabById(this.manifest.id);
      }
    });
    this.addSettingTab(new GDriveSyncSettingTab(this.app, this));
    this.registerObsidianProtocolHandler("gdrive-sync", async (params) => {
      try {
        const raw = params.code ? `http://127.0.0.1/?code=${encodeURIComponent(params.code)}` : params.url || "";
        if (!raw && !params.code) {
          new import_obsidian5.Notice("GDrive Sync: no auth code in URL");
          return;
        }
        await this.completeManualAuth(params.code || raw);
        new import_obsidian5.Notice("Google Drive Sync connected");
      } catch (e) {
        new import_obsidian5.Notice(`GDrive auth failed: ${String(e)}`);
      }
    });
    this.engine = new SyncEngine(this.app, this.settings, {
      onStatus: (status, detail) => this.setStatus(status, detail),
      saveSettings: () => this.saveSettings()
    });
    if (this.settings.tokens?.refreshToken) {
      this.initDrive();
    }
    this.registerEvent(
      this.app.vault.on("create", (f) => this.engine?.onLocalCreateOrModify(f))
    );
    this.registerEvent(
      this.app.vault.on("modify", (f) => this.engine?.onLocalCreateOrModify(f))
    );
    this.registerEvent(
      this.app.vault.on("delete", (f) => this.engine?.onLocalDelete(f))
    );
    this.registerEvent(
      this.app.vault.on(
        "rename",
        (f, oldPath) => this.engine?.onLocalRename(f, oldPath)
      )
    );
    this.app.workspace.onLayoutReady(() => {
      this.restartAutoSync();
      if (this.settings.tokens?.refreshToken && this.settings.autoSync) {
        window.setTimeout(() => void this.syncNow(false), 2500);
      }
    });
    const platformHint = import_obsidian5.Platform.isMobile ? "mobile" : import_obsidian5.Platform.isDesktopApp ? "desktop" : "app";
    console.log(`[GDrive Sync] loaded (${platformHint})`);
  }
  onunload() {
    this.oauth.cancelPending();
    if (this.pollTimer)
      clearInterval(this.pollTimer);
    this.pollTimer = null;
  }
  async loadSettings() {
    const data = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, data);
    if (!this.settings.syncIndex || this.settings.syncIndex.version !== 1) {
      this.settings.syncIndex = { version: 1, files: {} };
    }
    if (!this.settings.remoteFolderName) {
      this.settings.remoteFolderName = this.app.vault.getName();
    }
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.engine?.updateSettings(this.settings);
  }
  oauthConfig() {
    return {
      clientId: this.settings.clientId,
      clientSecret: this.settings.clientSecret,
      redirectUri: this.settings.redirectUri || DESKTOP_REDIRECT_URI
    };
  }
  initDrive() {
    if (!this.settings.tokens?.refreshToken || !this.settings.clientId) {
      this.drive = null;
      this.engine?.setDrive(null);
      return;
    }
    this.drive = new DriveClient(
      this.oauthConfig(),
      this.settings.tokens,
      async (tokens) => {
        this.settings.tokens = tokens;
        await this.saveSettings();
      }
    );
    this.engine?.setDrive(this.drive);
  }
  async connectGoogle() {
    if (!this.settings.clientId) {
      new import_obsidian5.Notice("Add your Google OAuth Client ID in settings first");
      return;
    }
    const config = this.oauthConfig();
    const isLoopback = this.oauth.usesLoopback(config.redirectUri);
    if (import_obsidian5.Platform.isDesktopApp && isLoopback) {
      new import_obsidian5.Notice("Complete Google sign-in in your browser\u2026");
      try {
        const tokens = await this.oauth.connectDesktop(config);
        await this.applyTokens(tokens);
        new import_obsidian5.Notice("Connected to Google Drive");
        await this.ensureRemoteFolder();
        await this.syncNow(false);
        return;
      } catch (e) {
        console.warn("[GDrive Sync] Desktop OAuth failed, opening manual flow", e);
        new import_obsidian5.Notice(
          "Automatic capture failed. Browser opened \u2014 paste the redirect URL in settings if needed."
        );
      }
    }
    this.oauth.openBrowserAuth(config);
    new import_obsidian5.Notice(
      isLoopback ? "Sign in, then paste the redirect URL (or code) in Google Drive Sync settings." : "Sign in with Google. You will return to your site \u2014 Obsidian should open, or paste the code in settings."
    );
  }
  async completeManualAuth(raw) {
    if (!this.settings.clientId) {
      throw new Error("Missing Client ID");
    }
    const config = this.oauthConfig();
    if (!this.oauth.getPendingState()) {
      this.oauth.beginAuth(config);
    }
    const tokens = await this.oauth.completeWithCode(config, raw);
    await this.applyTokens(tokens);
    await this.ensureRemoteFolder();
    new import_obsidian5.Notice("Connected to Google Drive");
    await this.syncNow(false);
  }
  async applyTokens(tokens) {
    this.settings.tokens = tokens;
    await this.saveSettings();
    this.initDrive();
    this.restartAutoSync();
  }
  async disconnectGoogle() {
    const token = this.settings.tokens?.refreshToken || this.settings.tokens?.accessToken;
    if (token)
      await revokeToken(token);
    this.settings.tokens = null;
    this.drive = null;
    this.engine?.setDrive(null);
    await this.saveSettings();
    this.restartAutoSync();
    this.setStatus("idle", "Disconnected");
  }
  async ensureRemoteFolder() {
    if (!this.drive)
      return;
    const name = this.settings.remoteFolderName.trim() || this.app.vault.getName();
    const { rootId, folderId } = await this.drive.ensureVaultFolder(name);
    this.settings.remoteFolderName = name;
    this.settings.remoteFolderId = folderId;
    this.settings.syncIndex.remoteFolderId = folderId;
    this.settings.syncIndex.remoteRootId = rootId;
    if (!this.settings.syncIndex.changeToken) {
      this.settings.syncIndex.changeToken = await this.drive.getStartPageToken();
    }
    await this.saveSettings();
  }
  async syncNow(notify = true) {
    if (!this.settings.tokens?.refreshToken) {
      if (notify)
        new import_obsidian5.Notice("Connect your Google account first");
      return;
    }
    this.initDrive();
    if (!this.engine)
      return;
    if (notify)
      new import_obsidian5.Notice("Syncing with Google Drive\u2026");
    await this.engine.sync();
    if (this.status === "idle" && notify) {
      new import_obsidian5.Notice("Google Drive sync complete");
    } else if (this.status === "error" && notify) {
      new import_obsidian5.Notice(`Sync error: ${this.statusDetail}`);
    }
  }
  restartAutoSync() {
    if (this.pollTimer) {
      clearInterval(this.pollTimer);
      this.pollTimer = null;
    }
    if (!this.settings.autoSync || !this.settings.tokens?.refreshToken)
      return;
    const ms = Math.max(15, this.settings.syncIntervalSeconds) * 1e3;
    this.pollTimer = setInterval(() => {
      void this.engine?.sync();
    }, ms);
  }
  setStatus(status, detail) {
    this.status = status;
    this.statusDetail = detail ?? "";
    if (!this.statusBarEl)
      return;
    this.statusBarEl.removeClass("is-error", "is-syncing");
    let text = "GDrive: Idle";
    if (status === "syncing") {
      text = "GDrive: Syncing\u2026";
      this.statusBarEl.addClass("is-syncing");
    } else if (status === "error") {
      text = `GDrive: Error`;
      this.statusBarEl.addClass("is-error");
      this.statusBarEl.setAttribute("aria-label", detail ?? "Error");
    } else if (status === "offline") {
      text = "GDrive: Offline";
    } else if (this.settings.lastSyncAt) {
      const t = new Date(this.settings.lastSyncAt).toLocaleTimeString();
      text = `GDrive: ${t}`;
    }
    this.statusBarEl.setText(text);
    if (detail)
      this.statusBarEl.title = detail;
  }
};
